#!/bin/bash
# Forked from https://github.com/SonarSource/re-ci-images/tree/master/docker/bin for using custom set_maven_build_version
# shellcheck source=/dev/null

set -euo pipefail

# use maven to set PROJECT_VERSION in the environment, call the promote function and notify burgr

source cirrus-env PROMOTE
source .cirrus/set_maven_build_version "$BUILD_NUMBER"
cirrus_jfrog_promote

#Add github commit status with build number
if [[ ! -v GITHUB_TOKEN ]]; then
    echo "GITHUB_TOKEN is not set"
else
    BUILD_URL="${ARTIFACTORY_URL}/webapp/#/builds/${PROJECT}/${BUILD_NUMBER}/"
    curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H 'Content-Type: application/json' --data '{"state": "success", "target_url": "'"${BUILD_URL}"'", "description": "Latest promoted build: '"${PROJECT_VERSION}"'", "context": "repox"}' https://api.github.com/repos/"${GITHUB_REPO}"/statuses/"${GIT_SHA1}"
fi

burgr-notify-promotion
