# QA pipeline at SonarSource
# Based on https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin

TARGET_PLATFORM:
  - e44
  - e45
  - e46
  - e47
  - e48

SQ_VERSION:
  - LTS
  - LATEST_RELEASE
  - DEV

exclude:
  - TARGET_PLATFORM: e44
    SQ_VERSION: LATEST_RELEASE
  - TARGET_PLATFORM: e44
    SQ_VERSION: DEV
  - TARGET_PLATFORM: e45
    SQ_VERSION: LTS
  - TARGET_PLATFORM: e45
    SQ_VERSION: DEV
  - TARGET_PLATFORM: e46
    SQ_VERSION: LTS
  - TARGET_PLATFORM: e46
    SQ_VERSION: DEV
  - TARGET_PLATFORM: e47
    SQ_VERSION: LTS
  - TARGET_PLATFORM: e47
    SQ_VERSION: DEV
  - TARGET_PLATFORM: e48
    SQ_VERSION: LTS
  - TARGET_PLATFORM: e48
    SQ_VERSION: LATEST_RELEASE
