name: Build
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: github-ubuntu-latest-s
    name: Build Project
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.9.12
      - name: Setup Maven Toolchains
        shell: bash
        run: .github/workflows/setup-maven-toolchains.sh
      - uses: SonarSource/ci-github-actions/get-build-number@v1
      - name: Setup DigiCert Client Tools
        uses: SonarSource/ci-github-actions/code-signing@v1
      - uses: SonarSource/ci-github-actions/config-maven@master # dogfood
        env:
          CURRENT_VERSION: skip
          PROJECT_VERSION: skip
        with:
          common-mvn-flags: -Declipse.p2.mirrors=false -Dmaven.install.skip=true -Dmaven.test.skip=true -Dsonar.skip=true -Dcyclonedx.skip=false
          artifactory-reader-role: private-reader
      - name: Custom versioning
        run: .cirrus/set_maven_build_version_github_action
      - uses: SonarSource/ci-github-actions/build-maven@master # dogfood
        with:
          maven-args: -Declipse.p2.mirrors=false -Dmaven.install.skip=true -DskipTests -Dmaven.deploy.skip=true -Djacoco.append=true -Dsonar.coverage.jacoco.xmlReportPaths=${CIRRUS_WORKING_DIR}/org.sonarlint.eclipse.core.tests/target/site/jacoco-aggregate/jacoco.xml
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
      - name: Upload site artifacts
        if: always() && !cancelled()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: site-zip
          path: org.sonarlint.eclipse.site/target/org.sonarlint.eclipse.site-*.zip

  validate:
    runs-on: github-ubuntu-latest-m
    name: Validate
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.9.12
      - name: Install UI test dependencies (Xvfb, metacity)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb metacity dbus-x11
      - name: Setup Maven Toolchains (JDK 11/17/21)
        shell: bash
        run: .github/workflows/setup-maven-toolchains.sh
      - uses: SonarSource/ci-github-actions/get-build-number@v1
      - uses: SonarSource/ci-github-actions/config-maven@master # dogfood
        env:
          CURRENT_VERSION: skip
          PROJECT_VERSION: skip
        with:
          artifactory-reader-role: private-reader
          common-mvn-flags: -Declipse.p2.mirrors=false -Dmaven.install.skip=true -Dsonar.skip=true
      - name: Run unit tests with Xvfb
        shell: bash
        env:
          DISPLAY: :10
        run: |
          # Start X server and window manager
          Xvfb :10 -screen 0 1920x1080x24 > Xvfb.out 2>&1 &
          metacity --sm-disable --replace &
          sleep 10
          # Execute tests with coverage
          mvn -X -B -e -V org.jacoco:jacoco-maven-plugin:prepare-agent verify \
            -Pcoverage \
            -Declipse.p2.mirrors=false \
            -Djacoco.append=true \
            -Djacoco.destFile=${GITHUB_WORKSPACE}/ut-coverage.exec
          ls -la ${GITHUB_WORKSPACE}/ut-coverage.exec

      - name: Upload UT coverage
        if: always() && !cancelled()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ut-coverage
          path: |
            ${{ github.workspace }}/ut-coverage*.exec

      - name: Upload Maven test logs
        if: always() && !cancelled()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mvn-test-logs
          path: 'org.sonarlint.eclipse.core.tests/target/work/configuration/*.log,org.sonarlint.eclipse.core.tests/target/work/data/.metadata/.log'

      - name: Upload Xvfb logs and JUnit XML on failure
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: failure-logs
          path: 'Xvfb.out,**/target/surefire-reports/TEST-*.xml'

      - name: Debug - Tree view of workspace
        shell: bash
        run: |
          echo "=== Tree view of GITHUB_WORKSPACE ==="
          tree -a "$GITHUB_WORKSPACE" || find "$GITHUB_WORKSPACE" -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'

      - name: Generate QA test report on failure
        if: failure()
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
        with:
          name: QA Validate Test Report
          reporter: java-junit
          path: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/*.xml'
          list-suites: failed
          list-tests: failed
          fail-on-empty: false

  qa_connectedModeSonarQube:
    needs: [build]
    runs-on: github-ubuntu-latest-m
    name: QA Connected Mode SonarQube
    permissions:
      id-token: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - SQ_VERSION: 'LATEST_RELEASE[9.9]'
            QA_CATEGORY: 'LATEST_RELEASE_99'
          - SQ_VERSION: 'LATEST_RELEASE'
            QA_CATEGORY: 'LATEST_RELEASE'
          - SQ_VERSION: 'DEV'
            QA_CATEGORY: 'DEV'
    env:
      DISPLAY: :10
      MAVEN_OPTS: -Xmx3072m
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.9.12

      - name: Install UI deps (Xvfb, metacity, ffmpeg)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb metacity dbus-x11 ffmpeg unzip

      - name: Setup Maven Toolchains (JDK 11/17/21)
        shell: bash
        run: .github/workflows/setup-maven-toolchains.sh
      - uses: SonarSource/ci-github-actions/get-build-number@v1
      - uses: SonarSource/ci-github-actions/config-maven@master # dogfood
        env:
          CURRENT_VERSION: skip
          PROJECT_VERSION: skip
        with:
          artifactory-reader-role: private-reader
          common-mvn-flags: -Declipse.p2.mirrors=false -Dmaven.install.skip=true -Dsonar.skip=true

      - name: Download site artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: site-zip
          path: site-artifact

      - name: Unpack site and detect P2 repo dir
        id: p2
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$GITHUB_WORKSPACE/staged-repository"
          ZIP=$(ls -1 site-artifact/*.zip | head -n1)
          echo "Unzipping $ZIP"
          unzip -q "$ZIP" -d "$GITHUB_WORKSPACE/staged-repository"
          P2_DIR=$(find "$GITHUB_WORKSPACE/staged-repository" -type f \( -name 'artifacts.jar' -o -name 'artifacts.xml*' \) -printf '%h\n' | head -n1)
          if [ -z "$P2_DIR" ]; then
            echo "::error::Failed to locate P2 repository in unzipped site"
            exit 1
          fi
          echo "P2_DIR=$P2_DIR" | tee -a "$GITHUB_ENV"

      - name: Vault (GitHub token)
        id: secrets-gh
        uses: SonarSource/vault-action-wrapper@320bd31b03e5dacaac6be51bbbb15adf7caccc32 # 3.1.0
        with:
          secrets: |
            development/github/token/licenses-ro token | GITHUB_TOKEN;

      - name: Start Xvfb and recording
        shell: bash
        run: |
          Xvfb :10 -screen 0 1920x1080x24 > Xvfb.out 2>&1 &
          metacity --sm-disable --replace &
          sleep 10
          echo 'Recording tests on video'
          ffmpeg -loglevel warning -f x11grab -video_size 1920x1080 -i ${DISPLAY} -codec:v libx264 -r 12 "$GITHUB_WORKSPACE/recording_${{ matrix.QA_CATEGORY }}.mp4" &

      - name: Run ITs (Connected Mode with SonarQube) with Xvfb
        shell: bash
        working-directory: its
        env:
          SQ_VERSION: ${{ matrix.SQ_VERSION }}
          QA_CATEGORY: ${{ matrix.QA_CATEGORY }}
          GITHUB_TOKEN: ${{ fromJSON(steps.secrets-gh.outputs.vault).GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          echo "Run ITs on Eclipse latest Java 17 target and Server ${SQ_VERSION}"
          mvn -B -e -V org.jacoco:jacoco-maven-plugin:prepare-agent verify \
            -P coverage,\!standaloneMode,\!connectedModeSc,\!cdtIntegration \
            -Declipse.p2.mirrors=false \
            -Dtarget.platform=latest-java-17_e431 \
            -Dtycho.localArtifacts=ignore \
            -Dsonarlint-eclipse.p2.url="file://${P2_DIR}" \
            -Dsonar.runtimeVersion=${SQ_VERSION} \
            -Djacoco.append=true \
            -Djacoco.destFile=${GITHUB_WORKSPACE}/it-coverage.exec
          mv ${GITHUB_WORKSPACE}/it-coverage.exec ${GITHUB_WORKSPACE}/it-coverage-${QA_CATEGORY}.exec

      - name: Stop recording and Xvfb
        if: always()
        shell: bash
        run: |
          pkill -SIGINT -f ffmpeg || true
          for i in $(seq 1 30); do pgrep ffmpeg >/dev/null || break; sleep 1; done
          pkill -f Xvfb || true

      - name: Upload video
        if: always() && !cancelled()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: recording-${{ matrix.QA_CATEGORY }}
          path: ${{ github.workspace }}/recording_${{ matrix.QA_CATEGORY }}.mp4

      - name: Upload IT coverage
        if: always() && !cancelled()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: jacoco-it-${{ matrix.QA_CATEGORY }}
          path: ${{ github.workspace }}/it-coverage-${{ matrix.QA_CATEGORY }}.exec

      - name: Upload IT logs
        if: always() && !cancelled()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mvn-it-logs-${{ matrix.QA_CATEGORY }}
          path: 'its/**/target/work/configuration/*.log,its/**/target/work/data/.metadata/.log'

      - name: Upload failure diagnostics
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: failure-${{ matrix.QA_CATEGORY }}
          path: 'Xvfb.out,**/test-results/**/*.xml,**/target/surefire-reports/TEST-*.xml'

      - name: Debug - Tree view of workspace
        shell: bash
        run: |
          echo "=== Tree view of GITHUB_WORKSPACE ==="
          tree -a "$GITHUB_WORKSPACE" || find "$GITHUB_WORKSPACE" -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'

      - name: Generate QA test report on failure
        if: failure()
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
        with:
          name: QA ${{ matrix.QA_CATEGORY }} Test Report
          reporter: java-junit
          path: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/*.xml'
          list-suites: failed
          list-tests: failed
          fail-on-empty: false