name: Build
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: github-ubuntu-latest-s
    name: Build Project
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.9.12
      - name: Setup Maven Toolchains
        shell: bash
        run: |
          # Find installed Java versions
          JAVA_11_HOME=$( mise where java@11)
          JAVA_17_HOME=$( mise where java@17)
          JAVA_21_HOME=$( mise where java@21)
          
          # Export environment variables for toolchains
          echo "JAVA_HOME_11_X64=$JAVA_11_HOME" >> "$GITHUB_ENV"
          echo "JAVA_HOME_17_X64=$JAVA_17_HOME" >> "$GITHUB_ENV"
          echo "JAVA_HOME_21_X64=$JAVA_21_HOME" >> "$GITHUB_ENV"
          
          # Copy toolchains.xml to Maven config directory
          mkdir -p "$HOME/.m2"
          cp .cirrus/toolchains.xml "$HOME/.m2/toolchains.xml"
          
          echo "Maven toolchains configured:"
          echo "  JavaSE-11: $JAVA_11_HOME"
          echo "  JavaSE-17: $JAVA_17_HOME"
          echo "  JavaSE-21: $JAVA_21_HOME"

          # Ensure Maven/Tycho runtime uses Java 17 (needed by Tycho plugins compiled for 17)
          echo "JAVA_HOME=$JAVA_17_HOME" >> "$GITHUB_ENV"
          echo "$JAVA_17_HOME/bin" >> "$GITHUB_PATH"
          
          # Sanity checks
          java -version
          mvn -version
      - uses: SonarSource/ci-github-actions/get-build-number@v1
      - name: Setup DigiCert Client Tools
        uses: SonarSource/ci-github-actions/code-signing@v1
      - uses: SonarSource/ci-github-actions/config-maven@master # dogfood
        env:
          CURRENT_VERSION: skip
          PROJECT_VERSION: skip
        with:
          common-mvn-flags: -Declipse.p2.mirrors=false -Dmaven.install.skip=true -Dmaven.test.skip=true -Dsonar.skip=true -Dcyclonedx.skip=false
          artifactory-reader-role: private-reader
      - name: Custom versioning
        run: .cirrus/set_maven_build_version_github_action
      - uses: SonarSource/ci-github-actions/build-maven@master # dogfood
        with:
          maven-args: -Declipse.p2.mirrors=false -Dmaven.install.skip=true -DskipTests -Dmaven.deploy.skip=true -Djacoco.append=true -Dsonar.coverage.jacoco.xmlReportPaths=${CIRRUS_WORKING_DIR}/org.sonarlint.eclipse.core.tests/target/site/jacoco-aggregate/jacoco.xml
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
      - name: Upload site artifacts
        if: always() && !cancelled()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: site-zip
          path: org.sonarlint.eclipse.site/target/org.sonarlint.eclipse.site-*.zip
