name: Shadow scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: github-ubuntu-latest-s
    name: Scan on shadow platforms
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/get-build-number@v1
      - name: Set build version
        shell: bash
        run: |
          maven_expression() {
            mvn -q -N -Dtycho.mode=maven help:evaluate \
              -Dexpression="$1" -DforceStdout
          }
          export -f maven_expression
          bash .cirrus/set_maven_build_version_github_action "$BUILD_NUMBER"
      - uses: SonarSource/ci-github-actions/build-maven@master # dogfood
        with:
          maven-opts: -Declipse.p2.mirrors=false -Dmaven.install.skip=true -DskipTests -Dmaven.deploy.skip=true -Djacoco.append=true -Dsonar.coverage.jacoco.xmlReportPaths=${CIRRUS_WORKING_DIR}/org.sonarlint.eclipse.core.tests/target/site/jacoco-aggregate/jacoco.xml
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
      - name: Run IRIS sync
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "org.sonarsource.sonarlint.eclipse:sonarlint-eclipse-parent"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.sonarlint.eclipse:sonarlint-eclipse-parent"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.sonarlint.eclipse:sonarlint-eclipse-parent"
          shadow2_platform: "SQC-US"
